<a href="https://colab.research.google.com/github/geeta7777chavan-boop/python-practicals/blob/main/practical_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name : Geeta Santosh Chavan**

**Roll No. : AIDS-SY-A-66**

# **Practical No. 4**

# **Aim :**

Numerical Computation with NumPy
Perform different computations using the NumPy library.

# **Theory :**

**1. Explain the role of NumPy in the Python scientific computing ecosystem.**

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a rich collection of high-level mathematical functions to operate on these arrays efficiently.

**Role in the Ecosystem:**


*   It serves as the core foundation for the entire Python scientific computing stack.

*   Almost all major data science and scientific libraries (such as Pandas, SciPy, Matplotlib, Scikit-learn, TensorFlow, and PyTorch) are built on top of NumPy or use its array objects.

*   NumPy brings the computational power of low-level languages like C and Fortran into Python, making it suitable for high-performance numerical computations while keeping the code simple and readable.

*   It enables efficient handling of numerical data, linear algebra, random number generation, and broadcasting operations.

In short, NumPy is the backbone of Python’s data science and scientific computing ecosystem.



**2. Why is NumPy considered faster than pure Python computations?**

NumPy is significantly faster than pure Python (lists + loops) for numerical operations due to the following reasons:


*   Vectorized Operations: NumPy performs element-wise operations on entire arrays without explicit Python loops. These operations are implemented in optimized C code.
*   Contiguous Memory Layout: NumPy arrays store data in continuous memory blocks (homogeneous data type), enabling better cache utilization and faster access (locality of reference).


*   Fixed Data Types: Unlike Python lists (which store pointers to objects and require dynamic type checking), NumPy arrays use a fixed dtype, reducing overhead.
*   Compiled Code: Most NumPy functions are written in C/Fortran and use highly optimized libraries like BLAS and LAPACK.

As a result, NumPy can be 10x to 100x faster than equivalent pure Python code for large datasets.

**3. What types of mathematical operations can be performed using NumPy?**

NumPy supports a wide range of mathematical operations, including:


*   **Arithmetic Operations:** Addition, subtraction, multiplication, division, exponentiation (element-wise and matrix).

*   **Trigonometric Functions**: `sin()`, `cos()`, `tan()`, etc.
*   **Statistical Operations:** Mean, median, standard deviation, variance, min, max, sum, etc.


*   **Linear Algebra:** Matrix multiplication, dot product, eigenvalues, inverse, determinants `(numpy.linalg)`.


*   **Random Number Generation:** numpy.random module for uniform, normal, and other distributions.
*   Broadcasting: Performing operations on arrays of different shapes.
Universal Functions `(ufuncs)`: Fast element-wise operations like `sqrt()`, `log()`, `exp()`, etc.


These operations make NumPy ideal for scientific simulations, data analysis, and machine learning.

**4. Explain indexing and slicing in NumPy arrays.**

Indexing and Slicing in NumPy are powerful ways to access and modify elements in arrays, similar to Python lists but extended for multi-dimensional data.


*   **Basic Indexing:** Access single elements using indices (0-based).
Example: arr[0, 1] for 2D array.
*   **Slicing:** Extract sub-arrays using start:end:step syntax.
Example: arr[1:4, 2:] returns a portion of the array.

*   **Boolean Indexing:** Select elements based on conditions.
Example: arr[arr > 5]
*   **Fancy Indexing:** Use integer arrays to select specific rows/columns.


NumPy slicing creates views (not copies) by default, which is memory-efficient but requires caution when modifying data.

**5. How does NumPy integrate with libraries like:**

**a. Pandas**

Pandas is built directly on top of NumPy. Pandas DataFrame and Series internally use NumPy arrays for data storage. This allows seamless conversion between them `(df.to_numpy()` or `pd.Series.values)` and fast numerical operations on tabular data.

**b. Matplotlib**

Matplotlib accepts NumPy arrays directly for plotting. Functions like `plt.plot(), plt.scatter(), and plt.hist()` work efficiently with NumPy arrays, enabling fast visualization of numerical data.

**c. Scikit-learn**

Scikit-learn uses NumPy arrays as the standard input format for machine learning algorithms. Most estimators expect data as NumPy arrays (or objects that can be converted to them). NumPy also powers internal computations for preprocessing, model training, and evaluation in Scikit-learn.

# **Program :**

In [ ]:
import numpy as np
print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


In [ ]:
# 1. Create a NumPy array from a list
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

# 2. Perform basic arithmetic operations
print("Addition:", arr + 5)
print("Multiplication:", arr * 2)

# 3. Find sum and mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# 4. Reshape a 1D array to 2D
arr2d = arr.reshape(5, 1)
print("Reshaped Array:\n", arr2d)

# 5. Access specific elements using indexing
print("Element at index 2:", arr[2])
print("Elements from index 1 to 4:", arr[1:4])

Array: [10 20 30 40 50]
Addition: [15 25 35 45 55]
Multiplication: [ 20  40  60  80 100]
Sum: 150
Mean: 30.0
Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Element at index 2: 30
Elements from index 1 to 4: [20 30 40]


In [ ]:
# 6. Matrix addition and multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Addition:\n", A + B)
print("Matrix Multiplication:\n", np.dot(A, B))

# 7. Generate random numbers
np.random.seed(42)  # for reproducibility
random_arr = np.random.randint(1, 100, size=(5, 3))
print("Random Array:\n", random_arr)

# 8. Compute standard deviation and variance
print("Standard Deviation:", np.std(random_arr))
print("Variance:", np.var(random_arr))

# 9. Mathematical operations
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr[:3]))

# 10. Compare Python lists vs NumPy arrays (Performance)
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

# Python List
start = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
print("Python List Time:", time.time() - start)

# NumPy Array
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
result_np = arr1 + arr2
print("NumPy Array Time:", time.time() - start)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Random Array:
 [[52 93 15]
 [72 61 21]
 [83 87 75]
 [75 88 24]
 [ 3 22 53]]
Standard Deviation: 29.42666968735825
Variance: 865.9288888888889
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential: [2.20264658e+04 4.85165195e+08 1.06864746e+13]
Python List Time: 0.07762956619262695
NumPy Array Time: 0.006887674331665039


# **Conclusion**
In this practical, we explored NumPy, the core library for numerical computation in Python. NumPy provides fast, efficient multi-dimensional arrays and a wide range of mathematical functions that form the foundation of the Python scientific computing ecosystem. Its speed, vectorized operations, and seamless integration with libraries like Pandas, Matplotlib, and Scikit-learn make it an essential tool for data analysis, scientific computing, and machine learning.
Mastering NumPy enables faster computations and smoother workflows in any data-driven project.